[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$version"
version_scheme = "pep440"
major_version_zero = true
update_changelog_on_bump = true
version = "0.1.0"
version_files = [
    "pyproject.toml:^version",
    "iftracer/sdk/version.py"
]
